### ISSUE TITLE
Case-insensitive

### ISSUE THREAD

**Issue by HaoyangFan** [argparse4j/argparse4j#112]
When I use `Argument.choices()`, how do I make it ignore the case sensitivities of all possible choices?

For example, the argument `Hello`, `hello`, and even `heLLO` will all be accepted

Thanks

**Comment by jstuyts** [comment]
It looks like you are using one of:
* `CaseInsensitiveEnumArgumentType`
* `CaseInsensitiveEnumNameArgumentType`
* `CaseInsensitiveEnumStringArgumentType`
* `Arguments#caseInsensitiveEnumType`
* `Arguments#caseInsensitiveEnumStringType`

Use one of these instead:
* `ReflectArgumentType`
* `EnumStringArgumentType`
* `Argument#type(java.lang.Class<T>)`
* `Arguments#enumStringType`

**Comment by jstuyts** [comment]
No reply for over a week. Assuming the problem has been solved.
