### ISSUE TITLE
Add getter to ArgumentParser for the Argument's

### ISSUE THREAD

**Issue by tedyu** [argparse4j/argparse4j#114]
Currently there is no getter in ArgumentParser which returns the Argument's added to the Parser.

This issue is to add getter for the Argument's.

**Comment by jstuyts** [comment]
Can you provide a use case?

**Comment by tedyu** [comment]
Once the Argument's are obtained, the user can perform some sanity check on the Argument's.
e.g. default value matches data type specified for each Argument.

Thanks

**Comment by jstuyts** [comment]
I think you can easily test this with a unit test:
```
@Test
public void defaultOfFooHasCorrectType() {
    // Create parser

    // Parse command line without an explicit value for the argument

    // Assert value has the correct type and/or value
}
```

But that only works for statically defined parsers and arguments. I can't image people building a parser dynamically, but crazy stuff is being built all the time :wink:

Do you need it for dynamically built arguments? If so, it may be worth adding the method. The reason I need a good use case for adding it, is that adding the requested method would break backward compatibility of interface `ArgumentParser`.

**Comment by tedyu** [comment]
Yes. Dynamically built argument is one use case.

Thanks

**Comment by jstuyts** [comment]
But is it *your* current use case? I won't break backward compatibility for hypothetical scenarios.

Please clearly explain what it is that you need to be able to do. You have to provide solid arguments if you want features that break backward compatibility to get implemented.

**Comment by jstuyts** [comment]
I am closing this, because there was no response for more than a month.
