### ISSUE TITLE
Cannot add positional argument to mutually exclusive group despite being optional

### ISSUE THREAD

**Issue by njdoyle** [argparse4j/argparse4j#116]
I would like to have two arguments for providing input to my program: a `--inputfile FILE` argument or a positional `INPUT` argument. If neither argument was specified, input would be read from STDIN.
The `--inputfile` argument would read the provided file for input, the `INPUT` positional argument would be the program's input as a string provided on the command line.

I would like to make these options mutually exclusive.

I have tried the following:
```java
MutuallyExclusiveGroup inputGroup = argumentParser.addMutuallyExclusiveGroup("Input options");
inputGroup
	.addArgument("--inputfile")
	.action(Arguments.store())
	.type(Arguments.fileType().verifyIsFile().verifyCanRead())
	.metavar("FILE")
	.help("Specify a file from which to read input.");
inputGroup
	.addArgument("input")
	.metavar("INPUT")
	.nargs("?")
	.help("Program input.");
```

But I get this Exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: mutually exclusive arguments must be optional
	at argparse4j@0.8.1/net.sourceforge.argparse4j.internal.ArgumentImpl.<init>(ArgumentImpl.java:85)
	at argparse4j@0.8.1/net.sourceforge.argparse4j.internal.ArgumentParserImpl.addArgument(ArgumentParserImpl.java:102)
	at argparse4j@0.8.1/net.sourceforge.argparse4j.internal.ArgumentGroupImpl.addArgument(ArgumentGroupImpl.java:73)
	at argparse4j@0.8.1/net.sourceforge.argparse4j.internal.ArgumentGroupImpl.addArgument(ArgumentGroupImpl.java:40)
	at myprogram/test.MyProgram.main(MyProgram.java:159)
```

**Comment by jstuyts** [comment]
A positional argument is always required, so that is why the exception is thrown.

Making it possible for positional arguments to be optional has quite some impact (backward compatibility must be preserved, so lots of tests need to be added to ensure that), so I don't see this happening anytime soon.

I can see how this can be useful though. What if you used a positional argument together with a flag argument?
```
argumentParser.addArgument("input");
argumentParser.addArgument("-f", "--inputisfile").action(storeConst()).setConst(TRUE);
```
And then you can use it like this:
```
# Input from the command line
MyProgram "This is the input."
# Input from standard in (this is a common convention)
MyProgram -
# Input from a file
MyProgram filename.txt --inputisfile
```
