### ISSUE TITLE
optional nargs consumes required positional arguments and fails type validation

### ISSUE THREAD

**Issue by richard-engineering** [argparse4j/argparse4j#119]
Similar to #42, except instead of '*', it happens for '?' nargs.

```java
ArgumentParser parser = ArgumentParsers.newFor("filesummary").build()
                .defaultHelp(true)
                .description("summarizes files based on arguments");
        parser.addArgument("filename")
                .help("File to modify or summarize");
        parser.addArgument("-a")
                .type(Integer.class).nargs("?").setConst(0)
                .help("Alphabetize the file (destructive), ignoring optional characters");
```
Passing in args = `['-a', 'path/to/file']` raises an error since the positional argument isn't an integer.

**Comment by jstuyts** [comment]
In the Python implementation the result is the same. The following snippet:
```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('filename')
parser.add_argument('-a', type=int, const=0, nargs='?')
print parser.parse_args(['-a', 'path/to/file'])
```

Results in:
```
usage: main.py [-h] [-a [A]] filename
main.py: error: argument -a: invalid int value: 'path/to/file'
```

Your configuration for `-a` means that these cases are valid:
* It does not have to be present.
* It is followed by an integer.
* It is the last item in the array.

**Comment by richard-engineering** [comment]
Current workaround I am using is to assume the positional argument is always last and not pass it to the parser at all. Looking at the python docs I'm guessing I would have to implement my own custom action to be a nongreedy '?'. Not sure if that is something which would be useful for others, but it's not an issue for this library.

**Comment by richard-engineering** [comment]
Doesn't look like it is possible with argparse, no way to conditionally take an argument or return it to the stack. Some more information at https://stackoverflow.com/a/26986546 (an issue with the python argparse library)
