### ISSUE TITLE
Trouble compiling to jar

### ISSUE THREAD

**Issue by rjpruitt16** [argparse4j/argparse4j#129]
Error: Unable to initialize main class 
Cause by: Java.Lang.NoClassDefFoundError: net/sourceforge/argparser4j/inf/ArgumentParserException

**Comment by jstuyts** [comment]
Do you have the full build output? Which JDK are you using?

**Comment by rjpruitt16** [comment]
This error was due to me not combining the jars. However, I still see a warning that it compile parent jar. It does run correctly

**Comment by jstuyts** [comment]
If you do not give details about what warning you see, it is difficult for me to help you.

Can you provide the details if you think it is something that should be fixed, or can you close this issue if no action is needed? Thanks.

**Comment by rjpruitt16** [comment]
I switch to spring boot, and it works perfectly. I saw the warning with maven assembly plug-in. Thanks
